# Generated by Django 2.0.1 on 2018-05-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='creado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='modificado',
            new_name='update',
        ),
    ]
